#!/bin/sh
#SBATCH -A COMPUTERLAB-SL2-GPU
#SBATCH --time=01:00:00
#SBATCH -p ampere
#SBATCH --nodes 1
#SBATCH --gres=gpu:1
#SBATCH --gpu-bind=none

#In this case $1 should be the sweep id generated by wandb
srun python -m wandb agent "$1"