  launcher:
    account: COMPUTERLAB-SL2-GPU
    timeout_min: 60
    nodes: 1
    partition: ampere
    gres: "gpu:1"
    gpus_per_task: 1
  callbacks:
    my_callback:
      _target_: sheaf_nc.LogJobReturnCallback