_target_: models.hgnn_baselines.SetGNN
in_channels: '${num_features}'
out_channels: '${out_channels}'
n_heads: 1
hidden_channels: 64
num_layers: 1
dropout: 0.0
learn_mask: true
normalisation: ln
input_norm: true
num_classifier_layers: 1
classifier_hidden_dim: 64