_target_: models.sheaf_gnn.inductive.InductiveDiscreteBundleSheafDiffusion
args:
  _target_: models.sheaf_gnn.config.SheafModelArguments
  output_dim: 64
  edge_weights: false
sheaf_learner: '${sheaf_learner}'