defaults:
  - default

early_stopping:
  patience: 100
  monitor: valid/loss

model_checkpoint:
  dirpath: checkpoints/sheafnc_checkpoints
#  filename: '${model}-${dataset}'
  mode: 'max'
  save_top_k: 1
  monitor: 'valid/accuracy'
