defaults:
  - default

early_stopping:
  patience: 100
  mode: max
  monitor: valid/AUROC

model_checkpoint:
  dirpath: checkpoints/sheaflp_checkpoints
  mode: max
  save_top_k: 1
  monitor: valid/AUROC